<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="resources\icons\hamburger.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.4" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.4" />
    <PackageReference Include="Avalonia.Xaml.Interactions" Version="11.3.0.6" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.4">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Update="App.axaml" />
    <AvaloniaXaml Update="MainWindow.axaml" />
    <AvaloniaXaml Update="menus/top/TopMenu.axaml" />
    <AvaloniaXaml Update="menus/side/SideMenu.axaml" />
    <AvaloniaXaml Update="panels/CenterPanel.axaml" />
    <AvaloniaXaml Update="panels/StatusBar.axaml" />
    <AvaloniaXaml Update="panes/RightPane.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="App.axaml.cs">
      <DependentUpon>App.axaml</DependentUpon>
    </Compile>
    <Compile Update="MainWindow.axaml.cs">
      <DependentUpon>MainWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="menus/top/TopMenu.axaml.cs">
      <DependentUpon>menus/top/TopMenu.axaml</DependentUpon>
    </Compile>
    <Compile Update="menus/side/SideMenu.axaml.cs">
      <DependentUpon>menus/side/SideMenu.axaml</DependentUpon>
    </Compile>
    <Compile Update="panels/CenterPanel.axaml.cs">
      <DependentUpon>panels/CenterPanel.axaml</DependentUpon>
    </Compile>
    <Compile Update="panels/StatusBar.axaml.cs">
      <DependentUpon>panels/StatusBar.axaml</DependentUpon>
    </Compile>
    <Compile Update="panes/RightPane.axaml.cs">
      <DependentUpon>panes/RightPane.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="resources\icons\hamburger.png" />
  </ItemGroup>
</Project>
